# Generated by Django 4.2.11 on 2026-05-02 01:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('input_text', models.TextField(blank=True, default='')),
                ('input_url', models.URLField(blank=True, default='')),
                ('input_audio', models.FileField(blank=True, null=True, upload_to='uploads/audio/')),
                ('input_video', models.FileField(blank=True, null=True, upload_to='uploads/video/')),
                ('result', models.JSONField(blank=True, null=True)),
                ('suspicious_words', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
